// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test/test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entity struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityAddReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityAddReq) Reset()         { *m = EntityAddReq{} }
func (m *EntityAddReq) String() string { return proto.CompactTextString(m) }
func (*EntityAddReq) ProtoMessage()    {}
func (*EntityAddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{1}
}

func (m *EntityAddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityAddReq.Unmarshal(m, b)
}
func (m *EntityAddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityAddReq.Marshal(b, m, deterministic)
}
func (m *EntityAddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityAddReq.Merge(m, src)
}
func (m *EntityAddReq) XXX_Size() int {
	return xxx_messageInfo_EntityAddReq.Size(m)
}
func (m *EntityAddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityAddReq.DiscardUnknown(m)
}

var xxx_messageInfo_EntityAddReq proto.InternalMessageInfo

func (m *EntityAddReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityAddRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityAddRes) Reset()         { *m = EntityAddRes{} }
func (m *EntityAddRes) String() string { return proto.CompactTextString(m) }
func (*EntityAddRes) ProtoMessage()    {}
func (*EntityAddRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{2}
}

func (m *EntityAddRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityAddRes.Unmarshal(m, b)
}
func (m *EntityAddRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityAddRes.Marshal(b, m, deterministic)
}
func (m *EntityAddRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityAddRes.Merge(m, src)
}
func (m *EntityAddRes) XXX_Size() int {
	return xxx_messageInfo_EntityAddRes.Size(m)
}
func (m *EntityAddRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityAddRes.DiscardUnknown(m)
}

var xxx_messageInfo_EntityAddRes proto.InternalMessageInfo

func (m *EntityAddRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityDelReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityDelReq) Reset()         { *m = EntityDelReq{} }
func (m *EntityDelReq) String() string { return proto.CompactTextString(m) }
func (*EntityDelReq) ProtoMessage()    {}
func (*EntityDelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{3}
}

func (m *EntityDelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityDelReq.Unmarshal(m, b)
}
func (m *EntityDelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityDelReq.Marshal(b, m, deterministic)
}
func (m *EntityDelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityDelReq.Merge(m, src)
}
func (m *EntityDelReq) XXX_Size() int {
	return xxx_messageInfo_EntityDelReq.Size(m)
}
func (m *EntityDelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityDelReq.DiscardUnknown(m)
}

var xxx_messageInfo_EntityDelReq proto.InternalMessageInfo

func (m *EntityDelReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityDelRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityDelRes) Reset()         { *m = EntityDelRes{} }
func (m *EntityDelRes) String() string { return proto.CompactTextString(m) }
func (*EntityDelRes) ProtoMessage()    {}
func (*EntityDelRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{4}
}

func (m *EntityDelRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityDelRes.Unmarshal(m, b)
}
func (m *EntityDelRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityDelRes.Marshal(b, m, deterministic)
}
func (m *EntityDelRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityDelRes.Merge(m, src)
}
func (m *EntityDelRes) XXX_Size() int {
	return xxx_messageInfo_EntityDelRes.Size(m)
}
func (m *EntityDelRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityDelRes.DiscardUnknown(m)
}

var xxx_messageInfo_EntityDelRes proto.InternalMessageInfo

func (m *EntityDelRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityUpdateReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityUpdateReq) Reset()         { *m = EntityUpdateReq{} }
func (m *EntityUpdateReq) String() string { return proto.CompactTextString(m) }
func (*EntityUpdateReq) ProtoMessage()    {}
func (*EntityUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{5}
}

func (m *EntityUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityUpdateReq.Unmarshal(m, b)
}
func (m *EntityUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityUpdateReq.Marshal(b, m, deterministic)
}
func (m *EntityUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityUpdateReq.Merge(m, src)
}
func (m *EntityUpdateReq) XXX_Size() int {
	return xxx_messageInfo_EntityUpdateReq.Size(m)
}
func (m *EntityUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_EntityUpdateReq proto.InternalMessageInfo

func (m *EntityUpdateReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityUpdateRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityUpdateRes) Reset()         { *m = EntityUpdateRes{} }
func (m *EntityUpdateRes) String() string { return proto.CompactTextString(m) }
func (*EntityUpdateRes) ProtoMessage()    {}
func (*EntityUpdateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{6}
}

func (m *EntityUpdateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityUpdateRes.Unmarshal(m, b)
}
func (m *EntityUpdateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityUpdateRes.Marshal(b, m, deterministic)
}
func (m *EntityUpdateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityUpdateRes.Merge(m, src)
}
func (m *EntityUpdateRes) XXX_Size() int {
	return xxx_messageInfo_EntityUpdateRes.Size(m)
}
func (m *EntityUpdateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityUpdateRes.DiscardUnknown(m)
}

var xxx_messageInfo_EntityUpdateRes proto.InternalMessageInfo

func (m *EntityUpdateRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityOneReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityOneReq) Reset()         { *m = EntityOneReq{} }
func (m *EntityOneReq) String() string { return proto.CompactTextString(m) }
func (*EntityOneReq) ProtoMessage()    {}
func (*EntityOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{7}
}

func (m *EntityOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityOneReq.Unmarshal(m, b)
}
func (m *EntityOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityOneReq.Marshal(b, m, deterministic)
}
func (m *EntityOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityOneReq.Merge(m, src)
}
func (m *EntityOneReq) XXX_Size() int {
	return xxx_messageInfo_EntityOneReq.Size(m)
}
func (m *EntityOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_EntityOneReq proto.InternalMessageInfo

func (m *EntityOneReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityOneRes struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityOneRes) Reset()         { *m = EntityOneRes{} }
func (m *EntityOneRes) String() string { return proto.CompactTextString(m) }
func (*EntityOneRes) ProtoMessage()    {}
func (*EntityOneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{8}
}

func (m *EntityOneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityOneRes.Unmarshal(m, b)
}
func (m *EntityOneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityOneRes.Marshal(b, m, deterministic)
}
func (m *EntityOneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityOneRes.Merge(m, src)
}
func (m *EntityOneRes) XXX_Size() int {
	return xxx_messageInfo_EntityOneRes.Size(m)
}
func (m *EntityOneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityOneRes.DiscardUnknown(m)
}

var xxx_messageInfo_EntityOneRes proto.InternalMessageInfo

func (m *EntityOneRes) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EntityPageReq struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityPageReq) Reset()         { *m = EntityPageReq{} }
func (m *EntityPageReq) String() string { return proto.CompactTextString(m) }
func (*EntityPageReq) ProtoMessage()    {}
func (*EntityPageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{9}
}

func (m *EntityPageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityPageReq.Unmarshal(m, b)
}
func (m *EntityPageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityPageReq.Marshal(b, m, deterministic)
}
func (m *EntityPageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityPageReq.Merge(m, src)
}
func (m *EntityPageReq) XXX_Size() int {
	return xxx_messageInfo_EntityPageReq.Size(m)
}
func (m *EntityPageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityPageReq.DiscardUnknown(m)
}

var xxx_messageInfo_EntityPageReq proto.InternalMessageInfo

func (m *EntityPageReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *EntityPageReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type EntityPageRes struct {
	Page                 int64     `protobuf:"varint,1,opt,name=page,proto3" json:"page"`
	Size                 int64     `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	TotalRecord          int64     `protobuf:"varint,3,opt,name=total_record,proto3" json:"total_record"`
	TotalPage            int64     `protobuf:"varint,4,opt,name=total_page,proto3" json:"total_page"`
	Data                 []*Entity `protobuf:"bytes,5,rep,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EntityPageRes) Reset()         { *m = EntityPageRes{} }
func (m *EntityPageRes) String() string { return proto.CompactTextString(m) }
func (*EntityPageRes) ProtoMessage()    {}
func (*EntityPageRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be09eee3772da7, []int{10}
}

func (m *EntityPageRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityPageRes.Unmarshal(m, b)
}
func (m *EntityPageRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityPageRes.Marshal(b, m, deterministic)
}
func (m *EntityPageRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityPageRes.Merge(m, src)
}
func (m *EntityPageRes) XXX_Size() int {
	return xxx_messageInfo_EntityPageRes.Size(m)
}
func (m *EntityPageRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityPageRes.DiscardUnknown(m)
}

var xxx_messageInfo_EntityPageRes proto.InternalMessageInfo

func (m *EntityPageRes) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *EntityPageRes) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *EntityPageRes) GetTotalRecord() int64 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *EntityPageRes) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *EntityPageRes) GetData() []*Entity {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "test.Entity")
	proto.RegisterType((*EntityAddReq)(nil), "test.EntityAddReq")
	proto.RegisterType((*EntityAddRes)(nil), "test.EntityAddRes")
	proto.RegisterType((*EntityDelReq)(nil), "test.EntityDelReq")
	proto.RegisterType((*EntityDelRes)(nil), "test.EntityDelRes")
	proto.RegisterType((*EntityUpdateReq)(nil), "test.EntityUpdateReq")
	proto.RegisterType((*EntityUpdateRes)(nil), "test.EntityUpdateRes")
	proto.RegisterType((*EntityOneReq)(nil), "test.EntityOneReq")
	proto.RegisterType((*EntityOneRes)(nil), "test.EntityOneRes")
	proto.RegisterType((*EntityPageReq)(nil), "test.EntityPageReq")
	proto.RegisterType((*EntityPageRes)(nil), "test.EntityPageRes")
}

func init() { proto.RegisterFile("proto/test/test.proto", fileDescriptor_86be09eee3772da7) }

var fileDescriptor_86be09eee3772da7 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0x01, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0x24,
	0xc1, 0xc5, 0xe6, 0x9a, 0x57, 0x92, 0x59, 0x52, 0x29, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x94, 0x99, 0xa2, 0x24, 0xc7, 0xc5, 0x03, 0x91, 0x71, 0x4c,
	0x49, 0x09, 0x4a, 0x2d, 0x24, 0x20, 0x5f, 0x8c, 0x5b, 0xde, 0x25, 0x35, 0x07, 0xaf, 0x7e, 0xb0,
	0x3c, 0xa6, 0x7e, 0x45, 0x2e, 0x7e, 0x88, 0x7c, 0x68, 0x41, 0x4a, 0x62, 0x49, 0x2a, 0x36, 0x23,
	0x30, 0x94, 0xe0, 0x71, 0x85, 0x7f, 0x5e, 0x2a, 0x5e, 0x57, 0x80, 0xe5, 0x31, 0xf5, 0x9b, 0x73,
	0xf1, 0x42, 0xe4, 0x03, 0x12, 0xd3, 0xc1, 0x06, 0x08, 0x71, 0xb1, 0x14, 0x24, 0xa6, 0xa7, 0x42,
	0x95, 0x80, 0xd9, 0x20, 0xb1, 0xe2, 0xcc, 0xaa, 0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0xad, 0x34,
	0x97, 0x11, 0x55, 0x67, 0x31, 0xb1, 0x3a, 0x85, 0x94, 0xb8, 0x78, 0x4a, 0xf2, 0x4b, 0x12, 0x73,
	0xe2, 0x8b, 0x52, 0x93, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0xc1, 0x72, 0x28, 0x62, 0x42, 0x72, 0x5c,
	0x5c, 0x10, 0x3e, 0xd8, 0x44, 0x16, 0xb0, 0x0a, 0x24, 0x11, 0x21, 0x05, 0x2e, 0x96, 0x94, 0xc4,
	0x92, 0x44, 0x09, 0x56, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x1e, 0x3d, 0x70, 0xbc, 0x43, 0x9c, 0x13,
	0x04, 0x96, 0x49, 0x62, 0x03, 0xa7, 0x02, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0xf9,
	0xb1, 0x68, 0x1e, 0x02, 0x00, 0x00,
}
