// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/aggregate/aggregate.proto

package aggregate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/aggregate/aggregate.proto", fileDescriptor_a9fa8af3bbc621ad) }

var fileDescriptor_a9fa8af3bbc621ad = []byte{
	// 54 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x4f, 0x2f, 0x4a, 0x4d, 0x4f, 0x2c, 0x49, 0x45, 0xb0, 0xf4, 0xc0, 0x32,
	0x42, 0x9c, 0x70, 0x81, 0x24, 0x36, 0xb0, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x61, 0xae,
	0xa1, 0x2e, 0x34, 0x00, 0x00, 0x00,
}
