// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/subscriber/subscriber.handler.proto

package subscriber

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Subscriber service

func NewSubscriberEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Subscriber service

type SubscriberService interface {
}

type subscriberService struct {
	c    client.Client
	name string
}

func NewSubscriberService(name string, c client.Client) SubscriberService {
	return &subscriberService{
		c:    c,
		name: name,
	}
}

// Server API for Subscriber service

type SubscriberHandler interface {
}

func RegisterSubscriberHandler(s server.Server, hdlr SubscriberHandler, opts ...server.HandlerOption) error {
	type subscriber interface {
	}
	type Subscriber struct {
		subscriber
	}
	h := &subscriberHandler{hdlr}
	return s.Handle(s.NewHandler(&Subscriber{h}, opts...))
}

type subscriberHandler struct {
	SubscriberHandler
}
