// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/subscriber/subscriber.proto

package subscriber

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/subscriber/subscriber.proto", fileDescriptor_cae8fa104cb8d9ea) }

var fileDescriptor_cae8fa104cb8d9ea = []byte{
	// 56 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x4d, 0x2a, 0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0x2d, 0x42, 0x62, 0xea, 0x81,
	0xe5, 0x84, 0xb8, 0x10, 0x22, 0x49, 0x6c, 0x60, 0x21, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x08, 0x88, 0x06, 0xea, 0x37, 0x00, 0x00, 0x00,
}
