// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/publisher/publisher.proto

package publisher

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EventT1 defined TODO
type EventT1 struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventT1) Reset()         { *m = EventT1{} }
func (m *EventT1) String() string { return proto.CompactTextString(m) }
func (*EventT1) ProtoMessage()    {}
func (*EventT1) Descriptor() ([]byte, []int) {
	return fileDescriptor_91d01b22eb7cdcad, []int{0}
}

func (m *EventT1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventT1.Unmarshal(m, b)
}
func (m *EventT1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventT1.Marshal(b, m, deterministic)
}
func (m *EventT1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventT1.Merge(m, src)
}
func (m *EventT1) XXX_Size() int {
	return xxx_messageInfo_EventT1.Size(m)
}
func (m *EventT1) XXX_DiscardUnknown() {
	xxx_messageInfo_EventT1.DiscardUnknown(m)
}

var xxx_messageInfo_EventT1 proto.InternalMessageInfo

func (m *EventT1) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventT1) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EventT1) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EventT1)(nil), "publisher.EventT1")
}

func init() { proto.RegisterFile("proto/publisher/publisher.proto", fileDescriptor_91d01b22eb7cdcad) }

var fileDescriptor_91d01b22eb7cdcad = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x28, 0x4d, 0xca, 0xc9, 0x2c, 0xce, 0x48, 0x2d, 0x42, 0xb0, 0xf4, 0xc0, 0x32,
	0x42, 0x9c, 0x70, 0x01, 0xa5, 0x40, 0x2e, 0x76, 0xd7, 0xb2, 0xd4, 0xbc, 0x92, 0x10, 0x43, 0x21,
	0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0x21,
	0x19, 0x2e, 0xce, 0x92, 0xcc, 0xdc, 0xd4, 0xe2, 0x92, 0xc4, 0xdc, 0x02, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0x84, 0x80, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa,
	0x04, 0x33, 0x58, 0x0b, 0x8c, 0x9b, 0xc4, 0x06, 0xb6, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0xb6, 0xc4, 0x4d, 0x87, 0x00, 0x00, 0x00,
}
