// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: publisher/publisher.handler.proto

package publisher

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Push service

func NewPushEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Push service

type PushService interface {
	PushEventT1(ctx context.Context, in *EventT1, opts ...client.CallOption) (*EventT1, error)
}

type pushService struct {
	c    client.Client
	name string
}

func NewPushService(name string, c client.Client) PushService {
	return &pushService{
		c:    c,
		name: name,
	}
}

func (c *pushService) PushEventT1(ctx context.Context, in *EventT1, opts ...client.CallOption) (*EventT1, error) {
	req := c.c.NewRequest(c.name, "Push.PushEventT1", in)
	out := new(EventT1)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Push service

type PushHandler interface {
	PushEventT1(context.Context, *EventT1, *EventT1) error
}

func RegisterPushHandler(s server.Server, hdlr PushHandler, opts ...server.HandlerOption) error {
	type push interface {
		PushEventT1(ctx context.Context, in *EventT1, out *EventT1) error
	}
	type Push struct {
		push
	}
	h := &pushHandler{hdlr}
	return s.Handle(s.NewHandler(&Push{h}, opts...))
}

type pushHandler struct {
	PushHandler
}

func (h *pushHandler) PushEventT1(ctx context.Context, in *EventT1, out *EventT1) error {
	return h.PushHandler.PushEventT1(ctx, in, out)
}
